### ISSUE TITLE
Can't serialize Vector3?

### ISSUE THREAD

**Issue by srlowe** [mviranyi/litjson#1]
For me,

`JsonMapper.ToJson( Vector3.one );`

Results it:

`JsonException: Max allowed object depth reached while trying to export from type UnityEngine.Vector3`

Any ideas?

**Comment by mviranyi** [comment]
Did you build the solution with Unity3D configuration? 

This means you need to have the preprocessor definition `UNITY3D` set. 

The JsonException happens when you haven't deployed the library for Unity3D. Then it recursively trys to serialize Vector3's internal normalized field, which is a Vector3 and thus again travels further into the infinite stack of serialization of that:

```
v3.normalized.normalized.normalized.normalized.normalized ... and so on
```

You can also try the latest v1.0.0 release which includes the ready to use library: https://github.com/mviranyi/litjson/releases/tag/v1.0.0
